trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - template: vars-global.yml

stages:
  - template: build-app.yml
  - template: deploy-app.yml
    parameters:
      environment: dev
      DependsOn: build
  - template: deploy-app.yml
    parameters:
      environment: qa
      DependsOn: 
      - build
      - deploy_dev

