stages:
- stage: build  
  jobs:
  - job: build
    variables:          
    - template: ./localfolder/local-var.yml@current
    steps:
    
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    
    - script: echo my local var ${{ variables.mylocalvar }} from my local var
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
    - powershell: Write-Host "##vso[task.setvariable variable=versionNumber;isOutput=true]1.1.0"
      name: versionnumber
      displayName: write variable=versionNumber   
