parameters:
- name: environment
  type: string
  default: ''
- name: DependsOn
  type: object

stages:
- stage: deploy_${{ parameters.environment }}
  dependsOn: ${{ parameters.DependsOn }}
  variables:          
    - template: vars-${{ parameters.environment }}.yml
    - template: ./localfolder/local-var.yml@current
    - name: version
      value: $[ stageDependencies.build.build.outputs['versionnumber.versionNumber'] ]    
  jobs:
  - deployment: DeploymentJob__${{ parameters.environment }}
    displayName: Deploy ${{ parameters.environment }}    
    environment: ${{ variables.environmentName }}
    strategy:    
      runOnce:
        deploy:
          steps:
          - script: echo my local var ${{ variables.mylocalvar }} from my local var
            displayName: 'Run a one-line script'
          - script: echo my first deployment ${{ variables.environmentName }} from variables
          - script: echo $(version)
            env:
              version: $(version)            
          - script: echo my first deployment ${{ parameters.environment }}  from parameters
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'env | sort'      
            
