parameters:
- name: environment
  type: string
  default: ''''

stages:
- stage: deploy
  variables:          
      - template: vars-${{ parameters.environment }}.yaml
  jobs:
  - deployment: DeploymentJob__${{ parameters.environment }}
    displayName: Deploy ${{ parameters.environment }}    
    environment: ${{ variables.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: Deploy appp!
            displayName: 'Deploy'
