parameters:
- name: environment
  type: string
  default: ''''

stages:
- stage: deploy
  variables:          
      - template: vars-${{ parameters.environment }}.yml
  jobs:
  - deployment: DeploymentJob__${{ parameters.environment }}
    displayName: Deploy ${{ parameters.environment }}    
    environment: ${{ variables.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - displayName: 'Deploy'
            script: 'Deploy app to ${{ variables.environmentName }}!'
            
