parameters:
- name: environment
  type: string
  default: ''

stages:
- stage: deploy_${{ parameters.environment }}
  variables:          
    - template: vars-${{ parameters.environment }}.yml
  jobs:
  - deployment: DeploymentJob__${{ parameters.environment }}
    displayName: Deploy ${{ parameters.environment }}    
    environment: ${{ variables.environmentName }}
    strategy:    
      runOnce:
        deploy:
          steps:           
          - script: echo my first deployment ${{ variables.environmentName }} from variables
          - script: echo my first deployment ${{ versionNumber }} from variables
          - script: echo my first deployment ${{ parameters.environment }}  from parameters
            
